id: datadog-log-shipper
namespace: company.team
tasks:
  - id: log_export
    type: io.kestra.plugin.ee.core.log.LogShipper
    logLevelFilter: INFO
    batchSize: 1000
    lookbackPeriod: P1D
    logExporters:
      - id: datadog
        type: io.kestra.plugin.ee.datadog.LogExporter
        basePath: https://http-intake.logs.datadoghq.eu
        apiKey: "{{ secret('DATADOG_API_KEY') }}"

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 7 * * *" # everyday at 7am

extend:
  title: Extract logs from Kestra and load them to Datadog
  description: Extracts logs from the Kestra backend and loads them to Datadog on a daily basis.
  tags:
    - DevOps
    - API
  ee: false
  demo: false
  meta_description: "Extracts logs from the Kestra backend and loads them to Datadog on a daily basis."