id: advanced-scheduling
namespace: sanitychecks
inputs:
  - id: country
    type: STRING
    defaults: US
  - id: date
    type: DATETIME
    required: false
    defaults: 2023-12-24T14:00:00.000Z
tasks:
  - id: check_if_business_date
    type: io.kestra.plugin.scripts.python.Commands
    warningOnStdErr: false
    namespaceFiles:
      enabled: true
    commands:
      - python schedule.py "{{trigger.date ?? inputs.date}}" {{inputs.country}}
    beforeCommands:
      - pip install workalendar
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: business day - continuing the flow...
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 14 25 12 *
