id: api-to-s3
namespace: sanitychecks
tasks:
  - id: get_pokemon
    type: io.kestra.plugin.core.http.Download
    method: GET
    uri: https://pokeapi.co/api/v2/pokemon/psyduck
  - id: upload
    type: io.kestra.plugin.aws.s3.Upload
    bucket: kestraio
    from: "{{ outputs.get_pokemon.uri }}"
    key: psyduck.json
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ secret('AWS_DEFAULT_REGION') }}"
triggers:
  - id: every_friday_afternoon
    type: io.kestra.plugin.core.trigger.Schedule
    timezone: Europe/Berlin
    cron: 0 17 * * FRI
