id: business-automation
namespace: sanitychecks
description: Business Automation
tasks:
  - id: working_directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: query
        type: io.kestra.plugin.jdbc.sqlite.Queries
        url: jdbc:sqlite:kestra.db
        fetchType: STORE
        sql: "CREATE TABLE IF NOT EXISTS features (\n    id INTEGER PRIMARY KEY,\n    name TEXT NOT NULL,\n    description TEXT NOT NULL,\n    release_version TEXT NOT NULL,\n    edition TEXT NOT NULL\n);\n\nDELETE FROM features;\n\nINSERT INTO features (name, description, release_version, edition)\nVALUES \n    ('Worker Groups', 'Allows targeting specific tasks or triggers to run on specific remote workers for better scalability and resource management.', '0.10', 'Enterprise'),\n    ('Realtime Triggers', 'Supports triggering event-driven workflows in real-time.', '0.17', 'Open-Source'),\n    ('Task Runners', 'Provides on-demand remote execution environments for running tasks.', '0.16', 'Open-Source'),\n    ('KV Store', 'Adds key-value storage for persisting data across workflow executions.', '0.18', 'Open-Source'),\n    ('SCIM Directory Sync', 'Allows synchronization of users and groups from Identity Providers.', '0.18', 'Enterprise');  \n    \nSELECT * FROM features\nORDER BY release_version;\n"
      - id: to_csv
        type: io.kestra.plugin.serdes.csv.IonToCsv
        from: "{{ outputs.query.outputs[0].uri }}"
      - id: to_excel
        type: io.kestra.plugin.serdes.excel.IonToExcel
        from: "{{ outputs.query.outputs[0].uri }}"
