id: ci-cd-github-webhook
namespace: sanitychecks
inputs:
  - id: payload
    type: JSON
tasks:
  - id: return
    type: io.kestra.plugin.core.debug.Return
    format: "{{ trigger.body.pull_request.comments_url ?? inputs.payload.pull_request.comments_url }}"
  - id: python_action
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: ghcr.io/kestra-io/pydata:latest
    script: |
      import requests
      import json

      url = "{{ outputs.return.value }}"

      headers = {
          'Authorization': 'token {{ secret('GITHUB_ACCESS_TOKEN') }}',
          'Accept': 'application/vnd.github.v3+json'
      }
      payload = {'body': 'hello from `{{ execution.id }}` in `{{ flow.id }}`'}
      response = requests.post(url, headers=headers, json=payload)

      if response.status_code == 201:
          print("Comment successfully created.")
      else:
          print(f"Failed to create comment: {response.text}")
triggers:
  - id: github
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: "{{ trigger.body.pull_request.state == 'open' and trigger.body.pull_request.comments_url }}"
