id: daily-flow
namespace: sanitychecks
tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: It's {{ trigger.date ?? taskrun.startDate | date("HH:mm") }}
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 30 6 * * *
