id: flow-condition-executionflow
namespace: sanitychecks
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: task of the triggered flow
triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionFlow
        flowId: system_flow
        namespace: system.prod
    states:
      - RUNNING
