id: flow-condition-executionlabels
namespace: company.team
tasks:
  - id: send_email
    type: io.kestra.plugin.notifications.mail.MailExecution
    to: john.doe@kestra.io
    from: hello@kestra.io
    subject: "The workflow execution {{ trigger.executionId }} failed for the flow {{ trigger.flowId }} in the namespace {{ trigger.namespace }}"
    host: mail.privateemail.com
    port: 465
    username: "{{ secret('EMAIL_USERNAME') }}"
    password: "{{ secret('EMAIL_PASSWORD') }}"
    executionId: "{{ trigger.executionId }}"
triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionLabels
        labels:
          owner: john.doe
    states:
      - FAILED
