id: flow-condition-executionstatus
namespace: sanitychecks
tasks:
  - id: send_slack_message
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ secret('SLACK_WEBHOOK') }}"
    channel: "#alert-engineering"
    executionId: "{{ trigger.executionId }}"
    payload: "The workflow execution {{ trigger.executionId }} failed for the flow {{ trigger.flowId }} in the namespace {{ trigger.namespace }}"
triggers:
  - id: flow
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
