id: parametrized-flow-with-multiple-schedules
namespace: company.team
inputs:
  - id: user
    type: STRING
    defaults: Data Engineer
    required: false
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.user }} from Kestra!
triggers:
  - id: quarter_hourly
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: "*/15 * * * *"
    inputs:
      name: user
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: "*/1 * * * *"
    inputs:
      name: user
      value: custom value
