id: runif-task-attribute
namespace: sanitychecks
inputs:
  - id: run_everything
    type: BOOLEAN
    defaults: true
tasks:
  - id: step1
    type: io.kestra.plugin.core.log.Log
    message: "This will always run"
  - id: step2
    type: io.kestra.plugin.core.log.Log
    runIf: "{{ inputs.run_everything }}"
    message: "This will only run if set to true"
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 10 * * *
    inputs:
      run_everything: true
