id: schedule-condition-dayweekinmonth
namespace: sanitychecks
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for DayWeekInMonth condition
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.DayWeekInMonth
        date: "{{ trigger.date }}"
        dayOfWeek: SATURDAY
        dayInMonth: LAST
