id: schedule-condition-datetimebetween
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for DateTimeBetween condition
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.DateTimeBetween
        date: "{{ trigger.date }}"
        before: "2025-01-01T00:00:00Z"
        after: "2025-12-31T23:59:59Z"
