id: schedule-condition-or
namespace: sanitychecks
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for Or condition
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.Or
        conditions:
          - type: io.kestra.plugin.core.condition.DayWeek
            date: "{{ trigger.date }}"
            dayOfWeek: MONDAY
          - type: io.kestra.plugin.core.condition.DayWeek
            date: "{{ trigger.date }}"
            dayOfWeek: THURSDAY
