id: taxi-trip-data
namespace: sanitychecks
tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: running backfill for file https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{ trigger.date ?? execution.startDate | date("yyyy-MM") }}.parquet
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 8 1 * *
    timezone: US/Eastern
    backfill:
      start: 2023-01-01T00:00:00Z
